steps:
  # Step 1: Build the Java code using Maven
  - name: 'maven:3.8.8-openjdk-17'
    entrypoint: 'mvn'
    args:
      - 'clean'
      - 'package'
      - '-DskipTests'

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_LOCATION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/spring-petclinic:$_TAG_NAME'
      - '.'

  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_LOCATION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/spring-petclinic:$_TAG_NAME'

images:
  - '$_LOCATION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/spring-petclinic:$_TAG_NAME'

substitutions:
  _PROJECT_ID: 'xebia-petclinic-dev'
  _REPOSITORY_NAME: 'petclinic-app'
  _LOCATION: 'europe-west1' # Adjust the region as needed
  _TAG_NAME: 'latest'

options:
  logging: CLOUD_LOGGING_ONLY