steps:
  - name: 'maven:3.9.4-eclipse-temurin-17'
    entrypoint: 'mvn'
    args:
      - 'clean'
      - 'package'
      - '-DskipTests'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_LOCATION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/spring-petclinic:$_TAG_NAME'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_LOCATION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/spring-petclinic:$_TAG_NAME'

  # Step 3: Trigger Cloud Deploy release with a unique release name
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'create-release'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        # Create the Cloud Deploy release
        gcloud deploy releases create pc-`date +%Y%m%d-%H%M%S` \
          --delivery-pipeline=petclinic-deploy-dev \
          --region=$_LOCATION \
          --annotations=commit_sha=$COMMIT_SHA \
          --images=spring-petclinic=$_LOCATION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/spring-petclinic:$_TAG_NAME

images:
  - '$_LOCATION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/spring-petclinic:$_TAG_NAME'

substitutions:
  _PROJECT_ID: 'xebia-petclinic-dev'
  _REPOSITORY_NAME: 'petclinic-app'
  _TAG_NAME: 'latest'
  _LOCATION: 'europe-west1'

options:
  logging: CLOUD_LOGGING_ONLY