steps:
  - name: 'maven:3.9.4-eclipse-temurin-17'
    entrypoint: 'mvn'
    args:
      - 'clean'
      - 'package'
      - '-DskipTests'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_LOCATION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/spring-petclinic:$_TAG_NAME'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_LOCATION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/spring-petclinic:$_TAG_NAME'

  # Step 3: Create a unique release name using a timestamp
  - name: 'bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        echo "petclinic-release-$TIMESTAMP" > /workspace/release_name.txt

  # Step 4: Trigger Cloud Deploy release
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        RELEASE_NAME=$(cat /workspace/release_name.txt)
        gcloud deploy releases create "$RELEASE_NAME" \
          --delivery-pipeline=petclinic-deploy-dev \
          --region=${_LOCATION} \
          --annotations=commit_sha=${COMMIT_SHA} \
          --images=spring-petclinic=${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_NAME}/spring-petclinic:${_TAG_NAME}

images:
  - '$_LOCATION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/spring-petclinic:$_TAG_NAME'

substitutions:
  _PROJECT_ID: 'xebia-petclinic-dev'
  _REPOSITORY_NAME: 'petclinic-app'
  _TAG_NAME: 'latest'
  _LOCATION: 'europe-west1'

options:
  logging: CLOUD_LOGGING_ONLY