apiVersion: skaffold/v3alpha1
kind: Config
metadata: 
  name: cloud-run-app
profiles:
- name: target-1
  manifests:
    rawYaml:
    - service.yaml
- name: target-2
  manifests:
    rawYaml:
    - service.yaml
deploy:
  cloudrun: {}