apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: petclinic-pipeline
description: Pipeline to deploy Cloud Run services for petclinic-app
serialPipeline:
  stages:
    - targetId: europe-west1
      profiles: [] # No profiles are being used here
#---
#apiVersion: deploy.cloud.google.com/v1
#kind: Target
#metadata:
#  name: us-west1
#description: Target for deploying to Cloud Run in us-west1
3run:
#  location: us-west1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: europe-west1
description: Target for deploying to Cloud Run in europe-west1
run:
  location: europe-west1