apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: petclinic-pipeline
description: Pipeline to deploy Cloud Run services for petclinic-app
serialPipeline:
  stages:
    - targetId: target-1
      profiles: [target-1] 
    - targetId: target-2
      profiles: [target-2]

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: target-1
description: Target for deploying to Cloud Run in europe-west1
run:
  location: projects/_PROJECT_ID/locations/europe-west1


---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: target-2
description: Target for deploying to Cloud Run in us-west1
run:
  location: projects/_PROJECT_ID/locations/us-west1