project_id        = "xebia-petclinic-dev"
region_primary    = "europe-west1"
region_secondary  = "us-west1"
service_image     = "europe-west1-docker.pkg.dev/xebia-petclinic-dev/petclinic-app/spring-petclinic:latest"
db_connection_name = "xebia-petclinic-dev:europe-west1:petclinic-dev-db"
